### ISSUE TITLE
Automation - Lux

### ISSUE THREAD

**Issue by snoopydooper** [estruyf/homebridge-solis-sensors#2]
Hello, me again! Thanks again so much.

Understand 1lux signifies 1kw.

Just an idea with automation I can only select when "lux rises above" 5, 10, 20, 50 ,100, 200, 400, 600, 1000, 1500 

My system is 5kw, so even on full power unlikely to trigger any automation (lux above 5)

If it is 1kw = 100 lux that could be more useful for automation but still able to understand at a glance.

Just an idea / suggestion :)

**Comment by estruyf** [comment]
That is correct. The idea of using lux came from another extension that did something similar for a power meter. Unfortunately, there is no support for power yet, so that is why they used Lux and used the same approach in this plugin.

What I can do is introduce a value multiplier (default: 100). Which means it will multiply all values by that number for each sensor. Think this way you get a bit more flexibility for your automation. 

Would that help?

**Comment by snoopydooper** [comment]
Yes please! Thank you :)

**Comment by estruyf** [comment]
I've added the `multiplier` property. You can set it to any value you want.
